name: soulflow
description: Resonant Universe.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # Core
  connectivity_plus: ^2.3.6+1 # Internet Checker
  dartz: ^0.10.1 # Either<Left, Right>
  go_router: ^4.4.1 # Routes
  # Model
  equatable: ^2.0.5 # Same Object Checker
  freezed_annotation: ^2.1.0  # Class Builder
  json_annotation: ^4.6.0 # JSON (De)Serializer
  uuid: ^3.0.6 # User ID generator
  # Data
  http: ^0.13.5 # Repo: Remote
  shared_preferences: ^2.0.11 # Repo: Local
  # Service
  flutter_bloc: ^8.1.1 # State Management
  flutter_hooks: ^0.18.2+1 # React Hooks, Code Reuse
  get_it: ^7.2.0 # Dependency Injection
  # Presentation
  badges: ^2.0.3
  bottom_navy_bar: ^6.0.0
  modal_bottom_sheet: ^2.1.2
  provider: ^6.0.3
  # lottie: # after_effects_rendering # https://xvrh.github.io/lottie-flutter-web/#/
  # sliding_up_panel # good for events? maybe
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1 # Test / Model
  freezed: ^2.1.0+1 # Model
  json_serializable: ^6.3.2 # Model

flutter:
  uses-material-design: true

 # assets:
  #  - assets
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#  scripts:
#    build:
#      name: "Build Mocks for Tests/Freezed Classes"
#      run: flutter pub run build_runner build --delete-conflicting-outputs
#
#    watch:
#      name: "Watch changes in Mocks for Tests/Freezed Classes"
#      run: flutter pub run build_runner watch
